### PR TITLE
Improved message labels.

### PR DESCRIPTION
**Pull request by MasterAM**
The unsub and nosub now attempt to fetch the original subscription
names.
It also tries to identify attempts to subscribe nonexsistent
publications (getting a nosub message without a matching unsub).

### CODE REVIEW

**Comment by callmephilip** [comment]
Hey Alon,

Thank you very much for the PR (and sorry for the lack of doc on contributions and such). I am gonna take a look at it later this week.

:palm_tree:

**Comment by callmephilip** [comment]
This looks very useful! A few comments regarding the PR:
- it would be great to get test coverage for these new labels (examples [here](https://github.com/thebakeryio/meteor-ddp-monitor/blob/master/__tests__/processors.js#L102))
- the case with inexistent subscription actually deserves to be treated as a [warning](https://github.com/thebakeryio/meteor-ddp-monitor/blob/master/src/warnings/user-overpublish.js)

**Comment by MasterAM** [comment]
I thought about warnings, but also about applying some styling to the label itself in those cases.

I intend to add warnings for unknown subscriptions and method responses that have an error argument.
I haven't gone over the entire codebase, but it seems that the `trece-processors` in the pipeline depend on the results of previous processors.

If that is the case, won't it be better to move that part of the `labels` processor that deals with `associations` (e.g, use the `request` key created by the `associations` processor in the `result` operation of the `label` processor)?

Regarding the tests, can you demonstrate how you make a dev build and run tests/dev server?
I want to make sure I'm doing this correctly.

**Comment by callmephilip** [comment]
regarding tests, here's an [updated doc](https://github.com/thebakeryio/meteor-ddp-monitor#development)

regarding processors, you are right about processors relying on the results from previous processors. the order is important and is defined [here](https://github.com/thebakeryio/meteor-ddp-monitor/blob/master/src/trace-processor.js#L17)

as far as separation of concerns, for me labeling is different from association and hence the split in the current implementation

**Comment by MasterAM** [comment]
Thanks for the docs.

I think that if the label processor relies on some relationships being computed by the relations processor and the relation between `subscription`, `ready`, `unsub` and `nosub` are well defined, they can be part of the job of the relations processor as well and used by the warning filter and the label processor.

Therefore, I am all for computing associations where they belong (I think that this is also what you meant, but I am not entirely sure) and using the results of the computation later on.

I am a bit swamped at the moment, but I will try to refactor and prepare some tests later this week.

**Comment by callmephilip** [comment]
Closing in favor of https://github.com/thebakeryio/meteor-ddp-monitor/pull/19. thank you @MasterAM

**Pull request closed without merging**
